<?php
// Automatically Generated by TestLink Installer - Thu, 04 Oct 18 10:58:33 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
